## Adding, removing, and sorting elements

In [1]:
import numpy as np

In [2]:
# Append

my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.append(my_arr, (10, 11, 12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

When axis is specified, values must have the correct shape.

In [4]:
my_arr1 = np.array([[1,2,3],
                    [2,4,6]])
my_arr1

array([[1, 2, 3],
       [2, 4, 6]])

In [5]:
np.append(my_arr1, [[2,1,1]])

array([1, 2, 3, 2, 4, 6, 2, 1, 1])

In [6]:
a = np.array([[1, 2, 8],
              [5, 8, 10]])

b = np.array([[8, 2, 1],
              [3, 9, 1]])

c = np.concatenate((a, b))
print(c)

[[ 1  2  8]
 [ 5  8 10]
 [ 8  2  1]
 [ 3  9  1]]


In [7]:
x = np.array([[1,2,3],
              [1,1,1]])

y = np.array([[3,3,1],
              [1,2,3]])

x = np.concatenate((x, y), axis = 1)
print(x)

[[1 2 3 3 3 1]
 [1 1 1 1 2 3]]


In [8]:
#Concatenate arrays

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [9]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0) #if axis = None, then arrays are flatten before use

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# sorting np.sort()
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)

[2 1 5 3 7 4 6 8]


In [12]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### delete elements of an array

In [13]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
np.delete(arr, 2, axis = 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

## Shape and Size of an array

`ndarray.ndim` : the number of axes \
`ndarray.size` : the total number of element \
`ndarray.shape` : the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [15]:
my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])

In [16]:
my_array.ndim

3

In [17]:
my_array.size

24

In [18]:
my_array.shape

(3, 2, 4)

### Reshaping an array

When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [19]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [20]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

## > Exercise 3

1. create a 3x3 matrix with values ranging from 2 to 10

In [51]:
x = np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. concentenate the following arrays \
**[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]**
![](lat3.png)

In [22]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])

c = np.concatenate((a,b), axis = 1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


### Converting a 1D array into 2D array (add a new axis to an array)

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

`np.newaxis` will increase the dimension of array by one whe it is used once. \
1D -> 2D, 2D -> 3D, and so on

In [23]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [24]:
# convert a 1D array to a row vector by inserting an axis along the first dimension
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [25]:
a2.shape

(1, 6)

In [26]:
# for a column vector, you can insert an axis along the second dimension
a3 = a[:, np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [27]:
a3.shape

(6, 1)

using `np.expand_dims`

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [29]:
# You can use np.expand_dims to add an axis at index position 1
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [30]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [31]:
# You can add an axis at index position 0 with
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [32]:
c

array([[1, 2, 3, 4, 5, 6]])

## Indexing and slicing

In [33]:
data = np.array([1, 2, 3, 4, 5])
data

array([1, 2, 3, 4, 5])

In [34]:
data[1]

2

In [35]:
data[:4]

array([1, 2, 3, 4])

In [36]:
data[0:2]

array([1, 2])

In [37]:
data[-2:]

array([4, 5])

![](numpy.jpg)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

## Subset

In [38]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [39]:
print(a[a < 5])

[1 2 3 4]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [40]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [41]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the & and | operators:

In [42]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [43]:
# pipe, or, vertical bar: |
five_up = (a > 5) | (a == 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [44]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a[1,1:3]

array([6, 7])

In [46]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
              
              [[0, 2, 4],
               [6, 8, 10]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [47]:
z.shape

(2, 2, 3)

In [48]:
z[0] # access row 0

array([[0, 1, 3],
       [5, 7, 9]])

In [49]:
z[0,1] # access row 0, column 1

array([5, 7, 9])

In [50]:
z[0, 1, 1:] #access row 1, column 1, depth 1-2

array([7, 9])

## > Exercise 4

1. create a null vector / 1D array of size 10 and update fifth value to 11.

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](lat1.png)